### ISSUE TITLE
popwin can not capture some windows.

### ISSUE THREAD

**Issue by stardiviner** [emacsorphanage/popwin#97]
;; for Debugger [C-g]

(push '(debugger-mode :position bottom :height 15) popwin:special-display-config)
(push "_Backtrack_" popwin:special-display-config)

;; for Org Agenda

(push '(org-agenda-mode :position bottom :height 15) popwin:special-display-config)
(push "_Agenda Commands_" popwin:special-display-config)

I set like this, but they does not work.

**Comment by sk8ingdom** [comment]
Sorry to re-open this @syohex, but I've tried the following without success.

`;; Mentioned above
(push '("*Org Agenda*" :height 15) popwin:special-display-config)
;; What I would really like to work
(push '("*Org Select*" :height 0.2 :noselect nil :stick t) popwin:special-display-config)
(push '("^CAPTURE-.+\*.org$" :regexp t) popwin:special-display-config)`

Have you been able to get this to work with org-agenda or org-capture? Thanks for your help!

**Comment by syohex** [comment]
Sorry too late reply. But popwin works well with your configuration. I added `:position` attribute for easy understanding behaviour.

```lisp
(push '("*Org Agenda*" :height 15 :position left) popwin:special-display-config)
;; What I would really like to work
(push '("*Org Select*" :height 0.2 :noselect nil :stick t) popwin:special-display-config)
(push '("^CAPTURE-.+\*.org$" :position left :regexp t) popwin:special-display-config)
```

Gif animation is here. If the configuration does not work, the windows are pop-uped at bottom of frame.

![popwin](https://cloud.githubusercontent.com/assets/554281/15063307/0a8848fa-1384-11e6-9174-765260d5dc60.gif)

**Comment by sk8ingdom** [comment]
@syohex, thanks for getting back to me. I can reproduce the `*Org Agenda*` configuration. Can you confirm that `*Org Select*` and `^CAPTURE.+\*.org$` are not correctly using popwin? I think the problem is with `org-switch-to-buffer-other-window`.

**My Version information**:
_M-x version_: GNU Emacs 24.4.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2014-10-20 on builder10-9.porkrind.org.
_Org-mode_: 20160509 from ELPA.
_popwin_: Most current build from Github.
_My Configuration_: [.emacs.d](https://github.com/sk8ingdom/.emacs.d), specifically [general-plugins.el](https://github.com/sk8ingdom/.emacs.d/blob/master/general-config/general-plugins.el).

**Comment by syohex** [comment]
popwin with your configuration works well for `*Org Select*` and `^CAPTURE.+\*.org$`.
NOTE: I added `:position left` attribute for easy understanding.

![popwin2](https://cloud.githubusercontent.com/assets/554281/15107676/1739d16a-160c-11e6-8955-120d565bf84d.gif)
